EnjoyBooking/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from EnjoyBooking.views import home_redirect
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path 
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accommodation/', include('accommodation.urls')),
    url(r'^accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    
    url(r'^', home_redirect, name='redirect'),    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accommodation/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "accommodation"

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^index/$', views.index_view, name='index'),
    url(r'^reservation/$', views.reservation_view, name='reservation'),
    url(r'^property/$', views.property_view, name='property'),
    url(r'^imageUploader/$', views.imageUploader_view, name='imageUploader'),
    path('propertyDetailed/<int:pk>/', views.propertyDetailed_view, name='propertyDetailed'),
    path('delete/<int:pk>/', views.deleteReservation_view, name='deleteReservation'),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"), 
    url(r'^profile/$', views.profile_view, name="profile"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accommodation/models.py
#!/usr/bin/env python
from django.db import models
from django.utils import timezone
from django_mysql.models import ListCharField
from accounts.models import CustomUser

# Create your models here.
class Accommodation(models.Model):
    seller = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=85)
    city = models.CharField(max_length=85)
    address = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=10)
    latitude = models.DecimalField(max_digits=19, decimal_places=15, default=0, null=True, blank=True)
    longitude = models.DecimalField(max_digits=19, decimal_places=15, default=0, null=True, blank=True)
    publication_date = models.DateTimeField(default=timezone.now)
    beds = models.PositiveSmallIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=500)
    services = ListCharField(
        base_field=models.CharField(max_length=50),
        size=40,
        max_length=(40*51))
    visible = models.BooleanField(default=True)
    def __str__(self):
        return self.name

def getAccImageName(instance, filename):
    return "accommodationImage/%s/%s" % (instance.accommodation_id, filename)

class AccommodationImage(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to=getAccImageName, verbose_name='Image')

class Reservation(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    checkin = models.DateField()
    checkout = models.DateField()
    paid = models.BooleanField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

accommodation/forms.py
from django import forms
from accommodation.models import Accommodation, Reservation, AccommodationImage

class PropertyCreationForm(forms.ModelForm):
    class Meta():
        model = Accommodation
        fields = ['name', 'country', 'city', 'address', 'postal_code', 'beds', 'price', 'services', 'description', 'visible']
        labels = {
            'postal_code': ('Postal code'),
        }
        widgets = {
            'services': forms.TextInput(attrs={'placeholder': 'Service1,Service2,...',})
        }

class PropertyChangeForm(forms.ModelForm):
    class Meta():
        model = Accommodation
        fields = ['name', 'country', 'city', 'address', 'postal_code', 'beds', 'price', 'services', 'description', 'visible']
        labels = {
            'postal_code': ('Postal code'),
        }

class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = AccommodationImage
        fields = ('image', )

class ReservationForm(forms.ModelForm):
    class Meta():
        model = Reservation
        fields = ('checkin', 'checkout',)


class SearchForm(forms.Form):
    service = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'placeholder': 'wifi,spa,cucina,...'}))
    inDate = forms.DateField(required=True)
    outDate = forms.DateField(required=True)

accommodation/views.py
#!/usr/bin/env python
import os
import datetime
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils import timezone
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from geopy import geocoders
from geopy.geocoders import GoogleV3
from accommodation.forms import PropertyCreationForm, PropertyImageForm, ReservationForm, PropertyChangeForm, SearchForm
from accommodation.models import Accommodation, AccommodationImage, Reservation



# Create your views here.
def index_view(request):
    #get top ten accommodation e images
    top10 = Accommodation.objects.filter(reservation__accommodation__in=Accommodation.objects.all(), visible=True).annotate(n_res=Count('reservation')).order_by('-n_res').distinct()[:10]
    top10image = AccommodationImage.objects.filter(accommodation_id__in=top10.values('id')).values('accommodation_id', 'image').order_by('id')

    #search accommmodations and get images
    if request.method=="POST":
        searchForm = SearchForm(request.POST)
        if searchForm.is_valid():
            services = searchForm.cleaned_data['service']
            services = services.split(",")
            inDate = searchForm.cleaned_data['inDate']
            outDate = searchForm.cleaned_data['outDate']
            reservedAccommodation = Reservation.objects.filter(checkin__lt=inDate, checkout__gt=inDate).values('accommodation_id').distinct()
            reservedAccommodation1 = Reservation.objects.filter(checkin__lt=outDate, checkout__gt=outDate).values('accommodation_id').distinct()
            reservedAccommodation2 = Reservation.objects.filter(checkin__gte=inDate, checkout__lte=outDate).values('accommodation_id').distinct()
            reservedAccommodation3 = Reservation.objects.filter(checkin__lt=inDate, checkout__gt=outDate).values('accommodation_id').distinct()
            reservedAccommodation = (reservedAccommodation | reservedAccommodation1 | reservedAccommodation2 | reservedAccommodation3).distinct()

            searchResult = Accommodation.objects.exclude(id__in=reservedAccommodation).order_by('price')

            if len(services) and services[0] != '':
                for result in searchResult:
                    for service in services:
                        if service not in result.services:
                            searchResult = searchResult.exclude(id=result.id)
            else:
                searchResult = searchResult

            if not len(searchResult):
                message = "No result with the selected services or dates."
            else:
                message= ""

            searchResultImage = AccommodationImage.objects.filter(accommodation_id__in=searchResult.values('id')).values('accommodation_id', 'image').order_by('id')
            return render(request, 'accommodation/index.html', {'searchForm':searchForm, 'searchResult':searchResult, 'searchResultImage':searchResultImage, 'top10':top10, 'top10image':top10image, 'message':message})  
    else:
        searchForm = SearchForm()      
        return render(request,'accommodation/index.html', {'searchForm':searchForm, 'top10':top10, 'top10image':top10image})

def getCoord(address):
    #insert correct API_KEY
    API_KEY = os.getenv("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    g = GoogleV3(api_key=API_KEY)

    coord=(0.0,0.0)
    try:
        location = g.geocode(address, timeout=15)
        coord = (location.latitude, location.longitude)
    except Exception as e:
        print('Impossible resolve:', e)
    return coord

#@login_required(redirect_field_name='accommodation:property')
def property_view(request):
    if not request.user.id == None:        
        if request.method == 'POST':
            form = PropertyCreationForm(request.POST)
            if form.is_valid():
                coord = getCoord(str(request.POST.get('country', '')+", "+request.POST.get('city', '')+", "+request.POST.get('postal_code', '')+", "+request.POST.get('address', '')))
                accommodation = form.save(commit=False)
                accommodation.seller = request.user
                accommodation.latitude = coord[0]
                accommodation.longitude = coord[1]
                accommodation.publication_date = timezone.now()
                accommodation.save()
                request.session['property_id'] = accommodation.pk
                return redirect('accommodation:imageUploader')
        else:
            form = PropertyCreationForm()
            property_list = Accommodation.objects.filter(seller=request.user)
            args = {'form':form, 'property_list':property_list}
            return render(request, 'accommodation/property.html', args)
    else:
        return render(request, 'accommodation/property.html')

def imageUploader_view(request):
    if request.method == 'POST':
        imgForm = PropertyImageForm(request.POST, request.FILES)
        if "exit" not in request.POST:
            if imgForm.is_valid():
                img = imgForm.save(commit=False)
                img.accommodation_id = request.session.get('property_id')
                img = imgForm.save()
            if "uploadNext" in request.POST:
                return redirect('accommodation:imageUploader')
            if "uploadExit" in request.POST:
                del request.session['property_id']
                return redirect('accommodation:property')
        else:
            del request.session['property_id']
            return redirect('accommodation:property')

    else:
        imgForm = PropertyImageForm()
        return render(request, 'accommodation/imageUploader.html', {'imgForm':imgForm,})


def getAvailableDateList(pk,reservationList):
    dateRanges = reservationList.values('checkin','checkout')
    dateList=[]
    for dateRange in dateRanges:
        days = (dateRange.get("checkout")-dateRange.get("checkin")).days
        for day in range(0,days):
            dateList.append(str(dateRange.get("checkin")+datetime.timedelta(days = day)))
    return dateList 


def propertyDetailed_view(request, pk):
    reservationForm = ReservationForm()
    try:
        propertyDetailed = Accommodation.objects.get(pk=pk)
    except Accommodation.DoesNotExist:
        raise Http404('This property does not exist')
    try:
        propertyImages = AccommodationImage.objects.filter(accommodation=pk).values('image')
    except AccommodationImage.DoesNotExist:
        print("No image found!")

    reservationList = Reservation.objects.filter(accommodation_id=pk, checkin__gte=datetime.date.today()).order_by('checkin')
    dateList = getAvailableDateList(pk,reservationList)

    if request.method == 'POST':
        modifyPropertyForm = PropertyChangeForm(request.POST, instance=propertyDetailed)
        if modifyPropertyForm.is_valid():
            modifyPropertyForm.save()

    modifyPropertyForm = PropertyChangeForm(instance=propertyDetailed)

    args =  {'propertyDetailed': propertyDetailed, 'propertyImages': propertyImages, 'reservationForm': reservationForm, 'modifyPropertyForm': modifyPropertyForm, 'dateList':dateList, 'reservationList':reservationList}
    return render(request, 'accommodation/propertyDetailed.html', args)

def reservation_view(request):
    if not request.user.id == None:
        if request.method == "POST":
            print(request.META.get('HTTP_REFERER'))

            reservationForm = ReservationForm(request.POST)
            if reservationForm.is_valid():
                reservation = reservationForm.save(commit=False)

                accommodation_id = request.META.get('HTTP_REFERER').strip('/').split('/')[-1]
                reservation.accommodation_id = accommodation_id
                reservation.user_id = request.user.id
                price = Accommodation.objects.get(pk=accommodation_id).price
                days = abs((reservation.checkout-reservation.checkin).days)
                reservation.total_price = price*days                
                reservation.paid = True
                reservation.save()

        newRes = Reservation.objects.filter(user=request.user, checkin__gte=datetime.date.today())
        oldRes = Reservation.objects.filter(user=request.user, checkin__lt=datetime.date.today())
        return render(request, 'accommodation/reservation.html', {'newReservations': newRes, 'oldReservations': oldRes})
    else:
        return render(request, 'accommodation/reservation.html')


def deleteReservation_view(request, pk):
    reservation = Reservation.objects.get(pk=pk)
    if request.user == reservation.user:
        if request.method == "POST":
            try:
                reservation.delete()
            except Reservation.DoesNotExist:
                raise Http404('This property does not exist')
            return redirect('accommodation:reservation')
        else:
            return render(request, 'accommodation/deleteReservation.html', {'reservation':reservation})
    else:
        return render(request, 'error403.html')
    

accommodation/templates/accommodation/deleteReservation.html
{% extends 'base_layout.html' %}
    
{% block content %}
    {% if user.is_authenticated %}
        <h1>Are you sure you want delete the following reservation?</h1>
        <h2>{{reservation.accommodation}} from {{reservation.checkin}} to {{reservation.checkout}}</h2>
        <form id="confirmDelete" action='{% url "accommodation:deleteReservation" pk=reservation.pk %}' method='post'>
            {% csrf_token %}    
            <button id="deleteButton" class="deleteFormBtn" value="delete" type="submit" name="deleteReservationButton" form="confirmDelete">Yes</button>
            <button id="cancelDeleteButton" class="deleteFormBtn" value="cancelDelete" onclick="location.href='{% url 'accommodation:reservation' %}'" type="button">Cancel</button>
        </form>
    {% endif %}
{% endblock %}

accommodation/templates/accommodation/imageUploader.html
{% extends 'base_layout.html' %}
    
{% block content %}

    {% if user.is_authenticated %}
    <div class="centerinPage">
        <form action="{% url 'accommodation:imageUploader' %}" method="post" id="fakeForm">{% csrf_token %}</form>
        <form action="{% url 'accommodation:imageUploader' %}" method="post" enctype="multipart/form-data">
            <table id="imageLoaderTable">
                {% csrf_token %}
                {{ imgForm }}
            </table>
            <div class="fill-div paddingTopBtn">
                <button type="submit" id="uploadNextBtn" name="uploadNext">Save and Upload Next</button>
                <button type="submit" id="uploadExit" name="uploadExit">Save and Exit</button>
                <button type="submit" id="exit" name="exit" value="exit" form="fakeForm">Exit</button>
            </div>
        </form>
    </div>

    {% else %}
        {% include error403 %}
    {% endif %}

{% endblock %}

accommodation/templates/accommodation/property.html
{% extends 'base_layout.html' %}
    
{% block content %}
 
    {% if user.is_authenticated %}

        <div class="propertyLeftColumn">
            <div id="propertyListDiv" class="propertyList">
                <h2>Here you can see all your property, open to modify.</h2>
            </div>
            {% if property_list %}
                <div id="propertyContainerHorizontal">
                    <table id="propertyTableList">
                        <thead id="propertyListHeader">
                            <th>Name</th>
                            <th>Address</th>
                            <th>Beds</th>
                            <th>Price</th>
                            <th>Services</th>
                            <th>Description</th>
                            <th>Publication Date</th>
                            <th>View</th>
                        </thead>
                        {% for property in property_list %}
                            <tr>
                                <td><a href='{% url "accommodation:propertyDetailed" pk=property.pk %}'><b>{{property.name}}</b></a</td>
                                <td>{{property.address}}, {{property.city}}, {{property.postal_code}}, {{property.country}}</td>
                                <td>{{property.beds}}</td>
                                <td>{{property.price}}</td>
                                <td>
                                    {% for service in property.services %}
                                        {% if not forloop.last %}
                                            {{service}},
                                        {% else %}
                                            {{service}}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{property.description}}</td>
                                <td>{{property.publication_date|date:"d/m/Y"}}</td>
                                <td><a href="{% url 'accommodation:propertyDetailed' pk=property.pk %}"><i class="arrow-green fas fa-arrow-right"></i></a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>

                <div id="propertyContainerVertical">
                    <table>
                        {% for property in property_list %}
                            <tr><th>Name</th><td><a href='{% url "accommodation:propertyDetailed" pk=property.pk %}'><b>{{property.name}}</b></a></td>
                            <tr><th>Address</th><td>{{property.address}}, {{property.city}}, {{property.postal_code}}, {{property.country}}</td></tr>
                            <tr><th>Beds</th><td>{{property.beds}}</td></tr>
                            <tr><th>Price</th><td>{{property.price}}</td></tr>
                            <tr><th>Services</th>
                                <td>
                                    {% for service in property.services %}
                                        {% if not forloop.last %}
                                            {{service}},
                                        {% else %}
                                            {{service}}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr><th>Description</th><td>{{property.description}}</td></tr>
                            <tr><th>Publication Date</th><td>{{property.publication_date|date:"d/m/Y"}}</td></tr>
                            <tr><td colspan="2"><a class="previewButton" href="{% url 'accommodation:propertyDetailed' pk=property.pk %}">View Preview <i class="arrow-green fas fa-arrow-right"></i></a></td></tr>
                            <tr style="min-height: 50px;"></tr>
                        {% endfor %}
                    </table>
                </div>
            {% else %}
                <div>Add a new property and start selling your accommodations.</div>
            {% endif %}

            <div id="showAddProperty" class="showAddProperty">
                <button id="showAddPropertyBtn" name="showAddProperty">Add Property</button>
            </div>
        </div>

        <div id="propertyRightColumn" class="propertyRightColumn">
            <div id="addPropertyForm" class="addProperty">
                <h2>Add new property</h2>
                <form class="property-form" action="{% url 'accommodation:property' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table id="propertyTable">
                        {{ form.as_table }}
                    </table>
                    <div class="containerUploadPropertyBtn">
                        <div class="uploadBtn"><input type="submit" id="addPropertyBtn" name="newAcc" value="Add Property"></div>
                        <div class="cancelUpload"><button id="cancelUpload" name="cancelUpload">Cancel</button></div>
                    </div>
                </form>
            </div>
        </div>   
        
    {% else %}
        <div class="infoBox">
            <div class="infoManager">
                <h3>
                    In this section you can easily list your property.
                </h3>  
                <h4>
                    You need to login or to register if you haven't already done.
                </h4>   
            </div>
            <div class="infoButton">
                <a href="{% url 'accounts:login' %}"><button>Login</button></a>&nbsp;
                <a href="{% url 'accounts:signup' %}"><button>Signup</button></a>
            </div>
        </div>
    {% endif %}
    
{% endblock %}

accommodation/templates/accommodation/propertyDetailed.html
{% extends 'base_layout.html' %}
    
{% block content %}

    <script>
        var array = {{ dateList|safe }};
        console.log(array);
    </script>
    <div class="detailedContainer">
        <div class="detailLeft">
            <div class="detailInfo">
                <h1>{{propertyDetailed.name}}</h1>
                <p>Created on: {{propertyDetailed.publication_date|date:"l, d F, Y"}}  <i class="far fa-calendar-alt"></i></p>

                <h3>Description</h3>
                <div id="descriptionDetailed">{{propertyDetailed.description}}</div>
                
                <h3>Services</h3>
                <div id="servicesDetailed">
                    <table>
                        {% for service in propertyDetailed.services %}
                            {% if forloop.counter0|divisibleby:2 %}
                                <tr><td><i class="fas fa-square"></i>  {{service}}</td>
                            {% else %}
                                <td><i class="fas fa-square"></i>  {{service}}</td></tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>

                <h3>Address</h3>
                <div id="addressDetailed">
                {{propertyDetailed.address}}, {{propertyDetailed.city}}, {{propertyDetailed.postal_code}}, {{propertyDetailed.country}}
                </div>

                <h3 id="priceLabel">Prezzo per notte: </h3><h2 id="price">€ {{propertyDetailed.price}}</h2>
                
                {% if user.is_authenticated %}

                <div id="bookData">
                    <div id="dataSelector">
                        <h3>Select Date and Book</h3>
                        <div>
                            <form id="bookForm" action="{% url 'accommodation:reservation' %}" method="post">
                                {% csrf_token %}
                                <table id="bookTable">
                                    {{reservationForm.as_table}}
                                </table>
                            </form>
                        </div>
                    </div>
                    <div id="priceCalc">
                        <h3>Total price</h3>
                        <h2 id="totalPrice">€ 0</h2>
                    </div>
                </div>
                <div id="detailBtn">    
                    <button id="bookProperty" value="Book" type="submit" name="bookProperty" form="bookForm"><i class="far fa-calendar-check"></i> Book</button>
                    {% if user == propertyDetailed.seller%}
                        <button id="modifyProperty"><i class="fas fa-edit"></i> Modify Property</button>
                    {% endif %} 
                </div>           
                {% else %}
                    <h2>You need to be authenticated for book a reservation.</h2>
                    <div >
                        <a href="{% url 'accounts:login' %}"><button class="greenButton">Login</button></a>&nbsp;
                        <a href="{% url 'accounts:signup' %}"><button class="greenButton">Signup</button></a>
                    </div>
                {% endif %}                 
            </div>
            
            {% if user == propertyDetailed.seller%}
            <div class="detailModify">
                <h1>Edit property information</h1>
                <form id="modifyPropertyForm" method="post"> {% comment %} action="{% url 'accommodation:propertyDetailed' pk=propertyDetailed.pk %}" {% endcomment %}
                    {% csrf_token %}
                    <table id="modifyPropertyTable">
                        {{modifyPropertyForm.as_table}}
                    </table>
                    <button id="saveModify" value="save" type="submit" name="saveModify" form="modifyPropertyForm"><i class="fas fa-save"></i> Update</button>
                </form>
            </div>

            <div id="futureReservation">
                <h2>Future reservations for this property</h2>
                {% if reservationList %}
                <table class="propertyReservationTable">
                    <thead class="propertyReservationTableHead">
                        <th>Guest Email</th>
                        <th>Check-in</th>
                        <th>Check-out</th>
                        <th>Total Cost</th>
                    </thead>
                    <tbody>
                    {% for reservation in reservationList %}
                        <tr>
                            <td class="alignCenter"><b>{{reservation.user}}</b></td>
                            <td class="alignCenter">{{reservation.checkin}}</td>
                            <td class="alignCenter">{{reservation.checkout}}</td>
                            <td class="alignCenter">€ {{reservation.total_price}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <div>No reservation for this property yet.</div>
                {% endif %}
            </div>
            {% endif %}
        </div>

        <div class="detailRight">
            <div class="detailPic">
                {% for image in propertyImages %}
                    <div class="picContainer">
                        <a href="/media/{{image.image}}" class="image-link">
                            <img src="/media/{{image.image}}" alt="/media/{{image.image}}">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

accommodation/templates/accommodation/reservation.html
{% extends 'base_layout.html' %}
    
{% block content %}
    {% if user.is_authenticated %}
        <div>
            <div class="reservationContainer">
                <h2 id="nextTitle" class="journeyTitle">Next journey</h2>
                {% if newReservations %}
                    <table class="reservationTable">
                        <thead class="reservationTableHead">
                            <th>Accommodation Name</th>
                            <th>Check-in</th>
                            <th>Check-out</th>
                            <th>Total Cost</th>
                            <th></th>
                        </thead>
                        <tbody>
                        {% for reservation in newReservations %}
                            <tr>
                                <td><b><a href="{% url 'accommodation:propertyDetailed' pk=reservation.accommodation.pk %}">{{reservation.accommodation}}</a></b></td>
                                <td class="alignCenter">{{reservation.checkin}}</td>
                                <td class="alignCenter">{{reservation.checkout}}</td>
                                <td class="alignCenter">€ {{reservation.total_price}}</td>
                                <td class="alignRight vertAlignCenter"><a href="{% url 'accommodation:deleteReservation' pk=reservation.pk %}"><i class="fas fa-trash-alt redIcon"></i></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div>No reservation in proress.</div>
                    <div><a id="searchLink" href="{%url 'accommodation:index' %}">Search some possible accommodation.</a></div>                  
                {% endif %}
            </div>


            <div class="reservationContainer">
                <h2 id="oldTitle" class="journeyTitle">Old journey</h2>
                {% if oldReservations %}
                    <table class="reservationTable">
                        <thead  class="reservationTableHead">
                            <th>Accommodation Name</th>
                            <th>Check-in</th>
                            <th>Check-out</th>
                            <th>Total Cost</th>
                        </thead>
                        <tbody>
                        {% for reservation in oldReservations %}
                            <tr>
                                <td><b>{{reservation.accommodation}}</b></td>
                                <td class="alignCenter">{{reservation.checkin}}</td>
                                <td class="alignCenter">{{reservation.checkout}}</td>
                                <td class="alignCenter">€ {{reservation.total_price}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div>There's no old reservation.</div>
                    
                {% endif %}
            </div>
        </div>

    {% else %}
        <div class="infoBox">
            <div class="infoManager">
                <h3>
                    In this section you can easily manage your reservation.<br>
                </h3>
                <h4>
                    You need to login or to register if you haven't already done.
                </h4>       
            </div>
            <div class="infoButton">
                <a href="{% url 'accounts:login' %}"><button>Login</button></a>&nbsp;
                <a href="{% url 'accounts:signup' %}"><button>Signup</button></a>
            </div>
        </div>
    {% endif %}    
{% endblock %}