EnjoyBooking/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from EnjoyBooking.views import home_redirect
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path 
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accommodation/', include('accommodation.urls')),
    url(r'^accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    
    url(r'^', home_redirect, name='redirect'),    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accommodation/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "accommodation"

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^index/$', views.index_view, name='index'),
    url(r'^reservation/$', views.reservation_view, name='reservation'),
    url(r'^property/$', views.property_view, name='property'),
    url(r'^imageUploader/$', views.imageUploader_view, name='imageUploader'),
    path('propertyDetailed/<int:pk>/', views.propertyDetailed_view, name='propertyDetailed'),
    path('delete/<int:pk>/', views.deleteReservation_view, name='deleteReservation'),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"), 
    url(r'^profile/$', views.profile_view, name="profile"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Enjoy Booking</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.ico' %} "/>
        <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'/>
        <link rel="stylesheet" type="text/css" href='{% static "js/jquery-ui-1.12.1.custom/jquery-ui.min.css" %}'>
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">        
        <link rel="stylesheet" type="text/css" href='{% static "js/viewbox-master/viewbox.css" %}'>
        
    </head>
    <body>
        <header class="headerWrapper">
            <div class="topnav" id="topnavMenu">
                <a id="logo" href="{%url 'accommodation:index'%}"><img src="{% static 'image/logo.jpg'%}" alt="EnjoyBooking"/></a>
                <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{%url 'accommodation:index'%}">Home</a>
                <a class="{% if request.resolver_match.url_name == 'reservation' %}active{% endif %}" href="{% url 'accommodation:reservation'%}">My Reservation</a>
                <a class="{% if request.resolver_match.url_name == 'property' %}active{% endif %}" href="{% url 'accommodation:property'%}">Your Property</a>

                {% if user.is_authenticated %}
                    <form id="logout-form" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}     
                        <a class="rightSide {% if request.resolver_match.url_name == 'logout' %}active{% endif %}" href="javascript:{}" onclick="document.getElementById('logout-form').submit();">Logout <i style="font-size:22px" class="fas fa-sign-out-alt"></i></a>                     
                    </form>
                    <a class="rightSide {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href="{% url 'accounts:profile' %}"><i style="font-size:20px" class="far fa-user"></i> {{ user.email }}</a>
                {% else %}
                    <a class="rightSide {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'accounts:login' %}">Login</a>
                    <a class="rightSide {% if request.resolver_match.url_name == 'signup' %}active{% endif %}" href="{% url 'accounts:signup' %}">Signup</a>                    
                {% endif %}

                <a href="javascript:void(0);" class="icon" onclick="responsiveMenuFunc()">
                    <i class="fas fa-align-justify"></i>
                </a>
            </div>
        </header>

        <div class="mainWrapper">
            {%block content%}
            {%endblock%}
        </div>
        <script type="text/javascript" src='{% static "js/jquery-3.3.1.min.js" %}'></script>
        <script type="text/javascript" src='{% static "js/jquery-ui-1.12.1.custom/jquery-ui.min.js" %}'></script>
        <script type="text/javascript" src='{% static "js/viewbox-master/jquery.viewbox.min.js" %}'></script>
        <script type="text/javascript" src='{% static "js/custom.js" %}'></script>
    </body>
</html>

templates/error403.html
{% extends 'base_layout.html' %}
    
{% block content %}

    <div class="Forbidden403">
        <h2>Access denied</h2> 
        <h3>Error 403</h3>
        {% if not user.is_authenticated %}
        <h3>The requested resource requires an authentication.</h3>
            <a href="{% url 'accounts:login' %}"><button class="greenButton">Login</button></a>&nbsp;
            <a href="{% url 'accounts:signup' %}"><button class="greenButton">Signup</button></a>
        {% endif %}
    </div>

{% endblock %}